config:
  jwt:
    # 加密密钥
    secret: kaN3f72qUB3BqUA
    # token有效时长
    expire: 3600
    # header 名称
    header: access-token
  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-bp18p2a901101o044fo.mysql.rds.aliyuncs.com:3306/contract?characterEncoding=utf-8
      username: root
      password: zyf227623!
    servlet:
      multipart:
        max-file-size: 500KB # 文件上传大小的限制，设置最大值
        max-request-size: 2MB #  文件最大请求限制，用于批量
  mybatis:
    mapper-locations: classpath:mapper/*.xml