mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp18p2a901101o044fo.mysql.rds.aliyuncs.com:3306/contract?characterEncoding=utf-8
    username: root
    password: zyf227623!